apiVersion: apps/v1
kind: Deployment
metadata:
  name: honbom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: honbom
  template:
    metadata:
      labels:
        app: honbom
    spec:
      containers:
      - image: okteto.dev/honbom:latest
        name: honbom
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "d0094d9a-9578-4c04-a579-f19a76f011d4"
        - name: Vless_Path
          value: "/d0094d9a-9578-4c04-a579-f19a76f011d4-vless"
        - name: Vmess_UUID
          value: "7866cd3d-2a01-4b31-93d2-0bfc35030144"
        - name: Vmess_Path
          value: "/7866cd3d-2a01-4b31-93d2-0bfc35030144-vmess"
        - name: Share_Path
          value: "$Share_Path"
